language: php

php:
  - 5.4

sudo: false

cache:
  directories:
    - ~/.composer/cache

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=9a7f8f9aad55cad5a085b638f1059086ab20d76b591e08f7393c5bdb0299f0cc ./bin/test-reporter
